#!/bin/bash

if [ $# -lt 1 ]
then
        echo "usage: $0 [cmd]"
        echo "'cmd' can be any git command, or the following: "
        echo "untracked -- lists all untracked dotfiles within " \
             "directories with one ore more tracked files."
fi

SCRIPT_PATH=$(dirname "$0")

case $1 in
        untracked)
                $SCRIPT_PATH/untracked
                ;;
        *)
                /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME "$@"
                ;;
esac
