#!/bin/bash


################################################################################
GIT_CMD="/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME"

usage () {
        echo "usage: $0 [cmd]"
        echo "'cmd' can be any git command, or the following: "
        echo "untracked -- lists all untracked dotfiles within " \
             "directories with one ore more tracked files."
}

untracked () {

    while read LINE
    do
            # checks for untracked files in directories
            [ -d $LINE ] && $GIT_CMD ls-files -o $LINE 
            
            # Creates a list of files/directories at the repo root
    done < <($GIT_CMD ls-files | sed -E 's,/.*$,,' | uniq)
}

################################################################################

if [ $# -lt 1 ]
then
        usage
        exit 1
fi

case "$1" in
        untracked)
                untracked
                ;;
        *)
                $GIT_CMD "$@"
                ;;
esac

exit 0
