#!/bin/bash
# SCRIPT: untracked
# AUTHOR: Alex Almanza
# DATE: 12/07/2017
# REV: 1.0
#
# PURPOSE: This script lists all untracked files of
#          tracked directories. 

SCRIPT_PATH=$(dirname "$0")

# command for executing the vc manager
config="$SCRIPT_PATH/config"

while read LINE
do
        # checks for untracked files in directories
        [ -d $LINE ] && $config ls-files -o $LINE 

        # Creates a list of files/directories at the repo root
done < <($config ls-files | sed -E 's,/.*$,,' | uniq)
